- name: win_chocolatey module example
  hosts: windows_servers
  gather_facts: False
  vars:
    - packages:
      - git
      - sublimetext4
      - notepadplusplus
      - googlechrome
      - docker-desktop

  tasks:
    - name: install packages
      win_chocolatey:
        name: "{{ packages }}"
        state: present