- name: Create user
  hosts: all
  become: true
  vars:
    user: edipcan
    ansible_ssh_private_key_file: "~/NVirginia-key.pem"
  tasks:
    - name: Create a user {{ user }}
      user:
        name: "{{ user }}"