- name: Copy for Linux
  hosts: webservers
  tasks:
    - name: Copy test file to the webservers
      ansible.builtin.copy:
        src: ~/playbook/testfile1
        dest: ~/testfile1
    
- name: Copy for ubuntu
  hosts: ubuntuservers
  tasks:    
    - name: Copy your file to the ubuntuservers
      ansible.builtin.copy:
        src: ~/playbook/testfile1
        dest: ~/testfile1