- name: Remove Apache from webservers
  hosts: webservers
  tasks:
    - name: Remove apache
      yum:
        name: httpd
        state: absent

- name: Remove Apache from ubuntuservers
  hosts: ubuntuservers
  tasks:
    - name: Remove apache
      apt:
        name: apache2
        state: absent

    - name: Remove unwanted Apache2 packages from the system
      apt:
        autoremove: yes
        purge: yes