- hosts: all
  become: yes
  vars_files:
    - secret.yaml
  tasks:
    - name: Add the user 
      ansible.builtin.user:
        name: "{{ username }}"
        password: "{{ password }}"
        state: present